version: '2.0'

services:
  
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - '27017:27017'
  redis:
    container_name: cache
    image: redis
    ports:
      - '6379:6379'

  spk-db:
    container_name: spk-db
    restart: always
    build:
      context: .
      dockerfile: ./spk-db/Dockerfile
    expose:
      - 3000
    ports:
      - '3000:3000'
    depends_on:
      - mongo
    links:
      - mongo
      - redis
    environment:
    - REDIS_URL=redis://cache
    volumes:
      - '.:/project/spk'

  